### PR TITLE
Fix #43

### LINKED ISSUE #43: Get-PowerBICapacity.md has a typo in the example
```Get-PowerBICapacity -Scope Organization -Show EncryptionKey``` 

should be probably be 

```Get-PowerBICapacity -Scope Organization -ShowEncryptionKey```

### PR DESCRIPTION
**Pull request by matt40k**
Fix for @dcrreynolds issue #43

### CODE REVIEW

**Comment by dcrreynolds** [comment]
Cool! Thanks @matt40k

**Comment by maggiesMSFT** [comment]
#sign-off 
Trying to sign off, just to see if I can, while we hunt for the repo owner.

**Review by CattieCat — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
Hi, @CattieCat -- thanks! When does master merge into live next?

**Comment by CattieCat** [comment]
@maggiesMSFT it's live now. https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.capacities/get-powerbicapacity?view=powerbi-ps

**Comment by maggiesMSFT** [comment]
@CattieCat -- great, thanks
cc @matt40k

**Pull request merged**
